/**
 * Laporan Retribusi API Service
 *
 * Handles all API calls related to Laporan Retribusi
 *
 * Last Updated: 2025-11-14
 */

import { apiClient } from './client'

export type LaporanStatus = 'draft' | 'submitted' | 'verified' | 'rejected'

export interface LaporanRetribusi {
  id: number
  nomorLaporan: string
  opdId: number
  opdKode: string
  opdNama: string
  jenisRetribusiId: number
  jenisRetribusiKode: string
  jenisRetribusiNama: string
  tanggalSetor: string
  nominal: string
  keterangan?: string
  fileBukti?: string
  status: LaporanStatus
  submittedBy: number
  submittedByName: string
  submittedAt?: string
  verifiedBy?: number
  verifiedAt?: string
  rejectionReason?: string
  createdAt: string
  updatedAt: string
}

export interface LaporanRetribusiListParams {
  page?: number
  limit?: number
  search?: string
  opdId?: number
  jenisRetribusiId?: number
  status?: LaporanStatus | 'all'
  startDate?: string
  endDate?: string
  sortBy?:
    | 'nomorLaporan'
    | 'tanggalSetor'
    | 'nominal'
    | 'status'
    | 'createdAt'
    | 'opdNama'
    | 'jenisRetribusiNama'
  sortOrder?: 'asc' | 'desc'
}

export interface LaporanRetribusiListResponse {
  success: boolean
  data: LaporanRetribusi[]
  pagination: {
    page: number
    limit: number
    total: number
    totalPages: number
  }
}

export interface LaporanRetribusiDetailResponse {
  success: boolean
  data: LaporanRetribusi
}

export interface LaporanRetribusiCreateData {
  opdId: number
  jenisRetribusiId: number
  tanggalSetor: string
  nominal: string
  keterangan?: string
  fileBukti?: string
  // nomorLaporan will be auto-generated by backend
}

export interface LaporanRetribusiUpdateData {
  nomorLaporan?: string
  opdId?: number
  jenisRetribusiId?: number
  tanggalSetor?: string
  nominal?: string
  keterangan?: string
  fileBukti?: string
}

export interface LaporanRetribusiResponse {
  success: boolean
  message: string
  data?: LaporanRetribusi
}

// Get Laporan Retribusi list with pagination and filters
export const getLaporanRetribusiList = async (
  params?: LaporanRetribusiListParams
): Promise<LaporanRetribusiListResponse> => {
  const queryParams = new URLSearchParams()

  if (params?.page) queryParams.append('page', params.page.toString())
  if (params?.limit) queryParams.append('limit', params.limit.toString())
  if (params?.search) queryParams.append('search', params.search)
  if (params?.opdId) queryParams.append('opdId', params.opdId.toString())
  if (params?.jenisRetribusiId)
    queryParams.append('jenisRetribusiId', params.jenisRetribusiId.toString())
  if (params?.status) queryParams.append('status', params.status)
  if (params?.startDate) queryParams.append('startDate', params.startDate)
  if (params?.endDate) queryParams.append('endDate', params.endDate)
  if (params?.sortBy) queryParams.append('sortBy', params.sortBy)
  if (params?.sortOrder) queryParams.append('sortOrder', params.sortOrder)

  const response = await apiClient.get<LaporanRetribusiListResponse>(
    `/api/laporan-retribusi?${queryParams.toString()}`
  )
  return response.data
}

// Get Laporan Retribusi detail by ID
export const getLaporanRetribusiDetail = async (
  id: number
): Promise<LaporanRetribusiDetailResponse> => {
  const response = await apiClient.get<LaporanRetribusiDetailResponse>(
    `/api/laporan-retribusi/${id}`
  )
  return response.data
}

// Create new Laporan Retribusi
export const createLaporanRetribusi = async (
  data: LaporanRetribusiCreateData | FormData,
  onUploadProgress?: (progress: number) => void
): Promise<LaporanRetribusiResponse> => {
  const response = await apiClient.post<LaporanRetribusiResponse>('/api/laporan-retribusi', data, {
    headers:
      data instanceof FormData
        ? {
            'Content-Type': 'multipart/form-data',
          }
        : undefined,
    onUploadProgress: (progressEvent) => {
      if (onUploadProgress && progressEvent.total) {
        const progress = Math.round((progressEvent.loaded * 100) / progressEvent.total)
        onUploadProgress(progress)
      }
    },
  })
  return response.data
}

// Update Laporan Retribusi
export const updateLaporanRetribusi = async (
  id: number,
  data: LaporanRetribusiUpdateData | FormData,
  onUploadProgress?: (progress: number) => void
): Promise<LaporanRetribusiResponse> => {
  const response = await apiClient.put<LaporanRetribusiResponse>(
    `/api/laporan-retribusi/${id}`,
    data,
    {
      headers:
        data instanceof FormData
          ? {
              'Content-Type': 'multipart/form-data',
            }
          : undefined,
      onUploadProgress: (progressEvent) => {
        if (onUploadProgress && progressEvent.total) {
          const progress = Math.round((progressEvent.loaded * 100) / progressEvent.total)
          onUploadProgress(progress)
        }
      },
    }
  )
  return response.data
}

// Delete Laporan Retribusi (soft delete)
export const deleteLaporanRetribusi = async (id: number): Promise<LaporanRetribusiResponse> => {
  const response = await apiClient.delete<LaporanRetribusiResponse>(`/api/laporan-retribusi/${id}`)
  return response.data
}

// Submit Laporan (draft → submitted)
export const submitLaporanRetribusi = async (id: number): Promise<LaporanRetribusiResponse> => {
  const response = await apiClient.post<LaporanRetribusiResponse>(
    `/api/laporan-retribusi/${id}/submit`
  )
  return response.data
}

// Reject Laporan (admin only, submitted → rejected)
export const rejectLaporanRetribusi = async (
  id: number,
  rejectionReason: string
): Promise<LaporanRetribusiResponse> => {
  const response = await apiClient.post<LaporanRetribusiResponse>(
    `/api/laporan-retribusi/${id}/reject`,
    { rejectionReason }
  )
  return response.data
}

export interface CheckDuplicateParams {
  opdId: number
  jenisRetribusiId: number
  tanggalSetor: string
  nominal: string
  excludeId?: number
}

export interface CheckDuplicateResponse {
  success: boolean
  exists: boolean
  data?: {
    id: number
    nomorLaporan: string
    status: string
    submittedByName: string
  }
}

// Check for duplicate laporan
export const checkDuplicateLaporan = async (
  params: CheckDuplicateParams
): Promise<CheckDuplicateResponse> => {
  const queryParams = new URLSearchParams({
    opdId: params.opdId.toString(),
    jenisRetribusiId: params.jenisRetribusiId.toString(),
    tanggalSetor: params.tanggalSetor,
    nominal: params.nominal,
  })
  if (params.excludeId) queryParams.append('excludeId', params.excludeId.toString())

  const response = await apiClient.get<CheckDuplicateResponse>(
    `/api/laporan-retribusi/check-duplicate?${queryParams.toString()}`
  )
  return response.data
}
